# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.0
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package Astro::Source::Finder;
use base qw(Exporter);
use base qw(DynaLoader);
package Astro::Source::Finderc;
bootstrap Astro::Source::Finder;
package Astro::Source::Finder;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package Astro::Source::Finder;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package Astro::Source::Finder;


############# Class : Astro::Source::Finder::Finder ##############

package Astro::Source::Finder::Finder;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( Astro::Source::Finder );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = Astro::Source::Finderc::new_Finder(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        Astro::Source::Finderc::delete_Finder($self);
        delete $OWNER{$self};
    }
}

*nearest = *Astro::Source::Finderc::Finder_nearest;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


# ------- VARIABLE STUBS --------

package Astro::Source::Finder;

1;
